export const AboutActions = {
  FETCH_ABOUT_REQUEST: 'FETCH_ABOUT_REQUEST',
  FETCH_ABOUT_SUCCESS: 'FETCH_ABOUT_SUCCESS',
  FETCH_ABOUT_FAILED: 'FETCH_ABOUT_FAILED',
  CREATE_ABOUT_REQUEST: 'CREATE_ABOUT_REQUEST',
  CREATE_ABOUT_SUCCESS: 'CREATE_ABOUT_SUCCESS',
  CREATE_ABOUT_FAILED: 'CREATE_ABOUT_FAILED',
  CREATE_ABOUT_VALIDATE: 'CREATE_ABOUT_VALIDATE',
  CLEAR_ABOUT: 'CLEAR_ABOUT'
}
