export const AdmissionActions = {
  FETCH_ADMISSION_REQUEST: 'FETCH_ADMISSION_REQUEST',
  FETCH_ADMISSION_SUCCESS: 'FETCH_ADMISSION_SUCCESS',
  FETCH_ADMISSION_FAILED: 'FETCH_ADMISSION_FAILED',
  CREATE_ADMISSION_REQUEST: 'CREATE_ADMISSION_REQUEST',
  CREATE_ADMISSION_SUCCESS: 'CREATE_ADMISSION_SUCCESS',
  CREATE_ADMISSION_FAILED: 'CREATE_ADMISSION_FAILED',
  CREATE_ADMISSION_VALIDATE: 'CREATE_ADMISSION_VALIDATE',
  CLEAR_ADMISSION: 'CLEAR_ADMISSION',
  EDIT_ADMISSION_REQUEST: 'EDIT_ADMISSION_REQUEST',
  EDIT_ADMISSION_SUCCESS: 'EDIT_ADMISSION_SUCCESS',
  EDIT_ADMISSION_FAILED: 'EDIT_ADMISSION_FAILED',
  DELETE_ADMISSION_REQUEST: 'DELETE_ADMISSION_REQUEST',
  DELETE_ADMISSION_SUCCESS: 'DELETE_ADMISSION_SUCCESS',
  DELETE_ADMISSION_FAILED: 'DELETE_ADMISSION_FAILED'
}
